#Integers between 1 and 10
odd = set([1,3,5,7,9])
even = set([2,4,6,8,10])
prime = set([2,3,5,7])
print(odd.union(even))
print(odd.union(odd))
print(odd.intersection(prime))
print(odd.intersection(even))
print(2 in prime)
print(6 in prime)
print(6 not in prime)